import Head from "next/head";
import React, { useState } from "react";
import { Container, Button, Carousel } from "react-bootstrap";
import Link from "next/link";
import newYork from "../public/images/new_york.jpg";
import cairo from "../public/images/cairo.jpg";
import seoul from "../public/images/seoul.jpg";
import sydney from "../public/images/sydney.jpg";
import rioDeJaneiro from "../public/images/rio_de_janeiro.jpg";
import paris from "../public/images/paris.jpg";
import Image from "next/image";
import "../styles/Home.module.scss";
import Header from "../components/header";
import Footer from "../components/footer";

export default function Home() {
  const [images, setImages] = useState([
    { name: "New York Image", image: newYork },
    { name: "Cairo Image", image: cairo },
    { name: "Seoul Image", image: seoul },
    { name: "Sydney Image", image: sydney },
    { name: "Rio De Janeiro Image", image: rioDeJaneiro },
    { name: "Paris Image", image: paris },
  ]);

  return (
    <>
      <Head>
        <title>Traveller App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container className="p-0 d-flex flex-column flex-fill" fluid id="home">
        <Carousel
          className="w-100 min-vh-100 position-absolute start-0 top-0"
          style={{ zIndex: "-1" }}
          controls={false}
          fade={true}
          indicators={false}
          interval={5000}
          keyboard={false}
          pause={false}
          touch={false}
          variant="dark"
        >
          {images.map((image, idx) => {
            return (
              <Carousel.Item className="h-100" key={`background-image-${idx}`}>
                <Image
                  className="bg-carousel-img"
                  src={image.image}
                  alt={image.name}
                />
              </Carousel.Item>
            );
          })}
        </Carousel>
        <div
          className="d-flex flex-fill flex-column justify-content-center align-items-end"
          id="landing"
        >
          <div
            className="d-flex flex-column gap-1 justify-content-center align-items-end "
            id="landing-text"
          >
            <h2>Travel App</h2>
            <h4>Plan your next trip with ease!</h4>
            <br />
            <p className="">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
            <div className="d-flex gap-2">
              <Link passHref legacyBehavior href="/register">
                <Button className="px-4" size="lg" variant="primary">
                  Sign Up
                </Button>
              </Link>
              <Link passHref legacyBehavior href="/login">
                <Button variant="dark" size="lg">
                  Sign In
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </Container>
    </>
  );
}
